### ISSUE TITLE
isFragmentRootElementName method access modifier should be protected [BATCH-2583]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1020]
**[Balan](https://jira.spring.io/secure/ViewProfile.jspa?name=balanjpm)** opened **[BATCH-2583](https://jira.spring.io/browse/BATCH-2583?redirect=false)** and commented

I was looking up to customize the method moveCursorToNextFragment in StaxEventItemReader and I noticed this method uses isFragmentRootElementName which is currently a private method. In my opinion, if caller is 'protected', the callee should have been made 'protected' as well.

---

**Affects:** 3.0.7

**Comment by benas** [comment]
> In my opinion, if caller is 'protected', the callee should have been made 'protected' as well.

That's not necessarily true, because if that private method calls another private method which in turn calls yet another private method, we would transitively need to make all of them protected  and end up opening the entire class for extension.

As a second example, the [jumpToItem](https://github.com/spring-projects/spring-batch/blob/a7092a21e428cf904f210aff2682b518dc3649c5/spring-batch-infrastructure/src/main/java/org/springframework/batch/item/xml/StaxEventItemReader.java#L273) is protected and calls [readToStartFragment](https://github.com/spring-projects/spring-batch/blob/a7092a21e428cf904f210aff2682b518dc3649c5/spring-batch-infrastructure/src/main/java/org/springframework/batch/item/xml/StaxEventItemReader.java#L295) and [readToEndFragment](https://github.com/spring-projects/spring-batch/blob/a7092a21e428cf904f210aff2682b518dc3649c5/spring-batch-infrastructure/src/main/java/org/springframework/batch/item/xml/StaxEventItemReader.java#L310) which are private. I don't think these two methods should necessarily be made protected.

That said, I see an added value in making `StaxEventItemReader#isFragmentRootElementName` protected to be able to override the logic in there.
