### ISSUE TITLE
SimpleStepExecutionSplitter queries lastStep by JobInstance and Stepname [BATCH-2550]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1052]
**[Georg Hendlmeier](https://jira.spring.io/secure/ViewProfile.jspa?name=gehen)** opened **[BATCH-2550](https://jira.spring.io/browse/BATCH-2550?redirect=false)** and commented

SimpleStepExecutionSplitter:245

If the job has nested partitions, then the job instance has more than one step execution with the same name derived from partition name. So it finds an already Starting StepExecution which leads to exception

SimpleStepExecutionSplitter:296

---

**Affects:** 3.0.7

**Comment by benas** [comment]
> SimpleStepExecutionSplitter:245

The code has changed since 2016 and line 245 [points to a Javadoc comment](https://github.com/spring-projects/spring-batch/blob/d8fc58338d3b059b67b5f777adc132d2564d7402/spring-batch-core/src/main/java/org/springframework/batch/core/partition/support/SimpleStepExecutionSplitter.java#L245) now. Please use a versioned link in the future when pointing to a specific line in the code. That said, I guess by "SimpleStepExecutionSplitter queries lastStep by JobInstance and Stepname" you mean [this line](https://github.com/spring-projects/spring-batch/blob/d8fc58338d3b059b67b5f777adc132d2564d7402/spring-batch-core/src/main/java/org/springframework/batch/core/partition/support/SimpleStepExecutionSplitter.java#L268), but please correct me if I'm wrong.

> If the job has nested partitions, then the job instance has more than one step execution with the same name derived from partition name

I don't understand what you mean by "nested partitions". Are you referring to the case of a partitioned step where each worker step is a in turn a partitioned step? If this is the case, I don't think the `SimpleStepExecutionSplitter` is designed for this kind of use cases (hence the "Simple" in its name?). You can always create a custom `StepExecutionSplitter` for advanced use cases.

I'm closing this issue for now. Please provide more details about the step configuration or a minimal project to reproduce the issue.
