### ISSUE TITLE
Problem with parallel job launching in Spring Batch [BATCH-2544]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1058]
**[Chaitanya](https://jira.spring.io/secure/ViewProfile.jspa?name=vchetu)** opened **[BATCH-2544](https://jira.spring.io/browse/BATCH-2544?redirect=false)** and commented

I have a situation to launch parallel job in Spring batch. We have exposed an API for file upload which we are inserting in Orient database. The UI make a call to underlying rest controller which launch a job for inserting the data. We are using SimpleAsyncTaskExecutor as well as SimpleJobLauncher for launching the job. We have observed that internal implementation of Spring batch is not synchronized once it inserts the created JobId into database, which cause two thread to get same jobId and cause TransactionRollBack exception. Also at each step the spring batch data management in DB(in memory Sql or external sql) is not synchronized.

We have referred to stack overflow other questions but increasing the concurrency limit as well using ThreadPoolTaskExecutor did not work. We think this because, spring batch internal implementation is not synchronized.

Any idea how we can achieve parallel job launch? Increasing application instance does not guarantee concurrency as it can not handle users more than number of instance.

---

**Affects:** 3.0.7

**Reference URL:** http://stackoverflow.com/questions/39898850/parallel-job-launch-issue-in-spring-batch

2 votes, 3 watchers

**Comment by benas** [comment]
When properly configured, the job repository acts as a safeguard against creating the same job instance in a clustered/multi-threaded environment. The transaction [isolationLevelForCreate](https://docs.spring.io/spring-batch/docs/4.2.x/api/org/springframework/batch/core/repository/support/AbstractJobRepositoryFactoryBean.html#setIsolationLevelForCreate-java.lang.String-) should be set to an aggressive value to achieve this.

You did not mention which code should be synchronized, but I see two options:

* Using the Map based job repository: this implementation uses concurrent data structures ([`ConcurrentMap`](https://github.com/spring-projects/spring-batch/blob/a7092a21e428cf904f210aff2682b518dc3649c5/spring-batch-core/src/main/java/org/springframework/batch/core/repository/dao/MapJobExecutionDao.java#L42), [`AtomicLong`](https://github.com/spring-projects/spring-batch/blob/7c1fbede1b53f1f6e00f6dd1dc614d1a99faf09c/spring-batch-core/src/main/java/org/springframework/batch/core/repository/dao/MapJobInstanceDao.java#L48), etc) behind the scene, so there is probably no need to synchronize access. That said, this implementation is clearly [documented](https://docs.spring.io/spring-batch/docs/4.2.x/api/org/springframework/batch/core/repository/support/MapJobRepositoryFactoryBean.html) to be not intended for production usage.
* Using the Jdbc job repository with an embedded db (or not): In this case, all "create*" methods will be transactional (for more details, take a look at the [`AbstractJobRepositoryFactoryBean#initializeProxy`](https://github.com/spring-projects/spring-batch/blob/d8fc58338d3b059b67b5f777adc132d2564d7402/spring-batch-core/src/main/java/org/springframework/batch/core/repository/support/AbstractJobRepositoryFactoryBean.java#L165) method that creates a transactional proxy around the job repository). So with a properly configured transaction attributes, it should be safe to launch multiple job instances in parallel thanks to the isolation guaranteed by the underlying database (be it in-memory or not).

BTW, the shared SO link is dead. I'm closing this issue for now, but feel to add a comment if you need help. Otherwise, please provide a minimal complete example that reproduces the issue.
