### ISSUE TITLE
Unable to get job step names when using java config [BATCH-2509]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1093]
**[Filip Hrisafov](https://jira.spring.io/secure/ViewProfile.jspa?name=filiphr)** opened **[BATCH-2509](https://jira.spring.io/browse/BATCH-2509?redirect=false)** and commented

When constructing a complex flow job with parallel using different `FlowBuilder`(s) then you cannot locate a step in the job.

The issue is that the `FlowBuilder` creates a `SimpleFlow` who's `afterPropertiesSet` method is never called which is responsible for populating the `stateMap` of the flow.

There is no issue during running of a Job (Flow) since the the initialize method is called in the start method of the flow.

---

**Affects:** 3.0.7

**Comment by benas** [comment]
> The issue is that the FlowBuilder creates a SimpleFlow who's afterPropertiesSet method is never called which is responsible for populating the stateMap of the flow.

[SimpleFlow](https://docs.spring.io/spring-batch/docs/4.2.x/api/org/springframework/batch/core/job/flow/support/SimpleFlow.html) declares that it implements `InitializingBean`, so the flow should be declared as a bean in order to honor its `InitializingBean` contract (aka Spring will automatically call its `afterPropertiesSet` method and the state map will be initialized as expected).

I'm closing this issue for now as I believe it is due to a misuse of the API, but feel free to add a comment with a minimal example if you disagree.
