### ISSUE TITLE
Section 8.1 (RepeatTemplate) erroneously refers to ExitStatus [BATCH-2484]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1119]
**[Joshua Hyde](https://jira.spring.io/secure/ViewProfile.jspa?name=jrh3k5)** opened **[BATCH-2484](https://jira.spring.io/browse/BATCH-2484?redirect=false)** and commented

Section 8.1 found here:

http://docs.spring.io/spring-batch/reference/html/repeat.html

...erroneously refers to the `RepeatCallback` returning an `ExitStatus` value when demonstrating how to use it with a `RepeatTemplate`.

Table 8.1 under section 8.1.2 also erroneously describes the table as containing `ExitStatus` values, despite the table actually being filled with `RepeatStatus` values.

Section 8.6 also makes reference to `ExitStatus` which is likely erroneous.

---
No further details from [BATCH-2484](https://jira.spring.io/browse/BATCH-2484?redirect=false)

**Comment by benas** [comment]
I do confirm. The 3.0.x docs were referring to `ExitStatus` instead of `RepeatStatus`: https://docs.spring.io/spring-batch/docs/3.0.x/reference/html/repeat.html#repeatTemplate.

However, this was fixed in https://github.com/spring-projects/spring-batch/commit/f6f01b5bb1bbfb4f34a6f7a1ef4119533492ea76 and the new docs are correct: https://docs.spring.io/spring-batch/docs/4.2.x/reference/html/repeat.html#repeat

I'm closing this as outdated.
