### ISSUE TITLE
IllegalAccessException when running JaCoCo [BATCH-2446]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1156]
**[Christian Weiss](https://jira.spring.io/secure/ViewProfile.jspa?name=chriweis)** opened **[BATCH-2446](https://jira.spring.io/browse/BATCH-2446?redirect=false)** and commented

Im MapStepExecutionDao on line 62 all fields of a class are set accessible. This conflicts with JaCoCo as it adds an synthetic field, thus an IllegalAccessException is thrown.
An easy fix is described in the reference URL.

---

**Affects:** 2.2.7

**Reference URL:** https://github.com/jacoco/eclemma/issues/59

**Issue Links:**
- [BATCH-2683](https://jira.spring.io/browse/BATCH-2683) Check field is not synthetic in BeanWrapperFieldExtractor

**Comment by benas** [comment]
This is similar to #1438. From JaCoCo [docs](https://www.jacoco.org/jacoco/trunk/doc/faq.html):

```
To collect execution data JaCoCo instruments the classes under test which adds two members to the classes: A private static field $jacocoData and a private static method $jacocoInit().
```

This static field added by JaCoCo should now be filtered after adding the `org.springframework.util.ReflectionUtils#COPYABLE_FIELDS` filter in [04b339b#diff-4b81841aff9fa792e2c71e7435d9e273R65](https://github.com/spring-projects/spring-batch/commit/04b339b8f4bcdfd8c1763b9c7568fee09e15c603#diff-4b81841aff9fa792e2c71e7435d9e273R65). So this issue is outdated and should be already fixed since v3.0.2.

> Affects: 2.2.7

Spring Batch v2 and v3 are not maintained anymore. The aforementioned commit is in the v4 line. If anyone faces the problem with v4+, please re-open this issue.
