### ISSUE TITLE
JobOperator needs a new method to pass parameters [BATCH-2438]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1165]
**[Petar Tahchiev](https://jira.spring.io/secure/ViewProfile.jspa?name=ptahchiev)** opened **[BATCH-2438](https://jira.spring.io/browse/BATCH-2438?redirect=false)** and commented

At the moment `JobOperator` has only the following method:

```
jobOperator.startNextInstance("ncsvImportJob");
```

There needs to be another method to also pass parameters like this:

```
jobOperator.startNextInstance("ncsvImportJob", parameters);
```

---
No further details from [BATCH-2438](https://jira.spring.io/browse/BATCH-2438?redirect=false)

**Comment by benas** [comment]
From the [`JobOperator#startNextInstance`](https://docs.spring.io/spring-batch/docs/4.2.x/api/org/springframework/batch/core/launch/JobOperator.html#startNextInstance-java.lang.String-) Javadoc:

```
Launch the next in a sequence of JobInstance determined by the JobParametersIncrementer attached to the specified job
```

This method will use the parameters calculated by the incrementer attached to the job. Adding a new method that takes another set of parameters would be confusing: Which parameters should take precedence, the ones passed in as a parameter or those returned by the incrementer?

The whole point of the job parameters incrementer API is to be able to start the next job instance without specifying any parameter (new parameters would be calculated from previous executions). What is suggested here goes against this idea.

I'm closing this issue for now because I fail to see a valid use case, but feel free to add a comment and we can re-open it for further discussion.
