### ISSUE TITLE
job scope bean doesn't cleanup in unit test

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1288]
**[Clockrun Ren](https://jira.spring.io/secure/ViewProfile.jspa?name=clockrun)** opened **[BATCH-2314](https://jira.spring.io/browse/BATCH-2314?redirect=false)** and commented

By using JobScopeTestExecutionListener in my test case (base on testng), I was able to instantiate job scope bean. however, after test method is executed, destroy() in job scope bean is never called.
After some investigation, I find there are issues in class JobScopeTestExecutionListener.

In method afterTestMethod, it will do JobSynchronizationManager.close(). which only remove scoped bean from context, without invoke of destroy(). if we use JobSynchronizationManager.release(), then everything is fine.

---

**Affects:** 3.0.1

**Comment by cppwfs** [comment]
Thank you for opening the issue.   Can you retry with the latest release of Spring Batch(5.0.2) and report back the results?   
If the issue is reproducible, can you provide a sample project that uses the latest release of Spring Batch and that exhibits the behavior?  To help you in reporting your issue, we have prepared a project template that you can use as a starting point. Please check the [Issue Reporting Guidelines](https://github.com/spring-projects/spring-batch/blob/main/ISSUE_REPORTING.md) for more details about this.
