### ISSUE TITLE
JobLauncherTestUtils fails when using `on` method from SimpleJobBuilder [BATCH-2285]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1320]
**[Josh Brackett](https://jira.spring.io/secure/ViewProfile.jspa?name=jbrackett)** opened **[BATCH-2285](https://jira.spring.io/browse/BATCH-2285?redirect=false)** and commented

If I create a job using:

> JobBuilderFactory jobs = new JobBuilderFactory(jobRepository);
> 
> return jobs.get("testJob").incrementer(new RunIdIncrementer()).start(step).on("*").to(step2).build().build();

then I get a failure that "No step found with name: ..."

Using

> return jobs.get("testJob").incrementer(new RunIdIncrementer()).start(step).next(step2).build();

works as expected.

Perhaps I'm just misunderstanding something or not configuring something correctly so I've created a simple project that replicates what I'm seeing.

---

**Affects:** 3.0.1

**Reference URL:** https://github.com/jbrackett/SpringBatchTestFailure

**Comment by benas** [comment]
Thanks for sharing a minimal example to reproduce the issue!

Without any code modification in the shared repo, the [test](https://github.com/jbrackett/SpringBatchTestFailure/blob/master/src/test/java/com/batch/failure/run/MinimumTestCase.java#L24) failing with v3.0.1 passes with Spring Batch v4.2.1.

Since Spring Batch v3 is not maintained anymore and the bug does not happen with v4.2.1, I'm closing this issue.
