### ISSUE TITLE
JobLocator should support the returns of boolean value that indicate whether the job exists by job name [BATCH-2132]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1463]
**[Simon Wong](https://jira.spring.io/secure/ViewProfile.jspa?name=simonwg)** opened **[BATCH-2132](https://jira.spring.io/browse/BATCH-2132?redirect=false)** and commented

If Spring Batch is configured as "modular", the JobRegistry might not have the latest job information because there is latency for registering the job.

For some situations (e.g. through Spring Integration), the batch job will be triggered earlier than the job registration in JobRegistry, which will result NoSuchJobException be thrown).

Currently, I have to catch NoSuchJobException, ignore it and waiting the next round of Spring Integration to trigger the batch job again (and hope the job is registered successfully in next round).

Catch the exception and ignore it looks ugly. It is better to add a boolean method, such as isJobExists(String jobName) in JobLocater

---

**Affects:** 2.2.2

**Comment by benas** [comment]
> For some situations [..] the batch job will be triggered earlier than the job registration in JobRegistry, which will result NoSuchJobException be thrown.

The `AutomaticJobRegistrar` has been updated to implement `SmartLifecycle` in #571. Since this registrar has the [lowest precedence](https://github.com/spring-projects/spring-batch/blob/main/spring-batch-core/src/main/java/org/springframework/batch/core/configuration/support/AutomaticJobRegistrar.java#L62), jobs will now be registered early enough during the application context startup and should be found as expected when requested from the `JobRegistry`. For this reason, and as mentioned in my previous comment, I see no need to add a new method in the `JobLocator` interface. I'm closing this as superseded by #1040.
