### ISSUE TITLE
Add (JOB_INSTANCE_ID) unique constraint to JobExecution table

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1475]
**[Erwin Vervaet](https://jira.spring.io/secure/ViewProfile.jspa?name=klr8)** opened **[BATCH-2120](https://jira.spring.io/browse/BATCH-2120?redirect=false)** and commented

As originally hinted at by [BATCH-1852](https://jira.spring.io/browse/BATCH-1852), very quick jobs are poorly identified.

JdbcJobExecutionDao.getLastJobExecution() assumes that the combination of the JOB_INSTANCE_ID and CREATE_TIME uniquely identifies a JobExecution instance:

```
SELECT JOB_EXECUTION_ID, START_TIME, END_TIME, STATUS, EXIT_CODE, EXIT_MESSAGE, CREATE_TIME, LAST_UPDATED, VERSION
from %PREFIX%JOB_EXECUTION
where JOB_INSTANCE_ID = ? and CREATE_TIME = (SELECT max(CREATE_TIME) from %PREFIX%JOB_EXECUTION where JOB_INSTANCE_ID = ?)
```

However, this is not enforced by a constraint in the database. This can give problems in certain situations, i.e. with fast running jobs on MySQL which does not have a millisecond data type (see http://forum.spring.io/forum/spring-projects/batch/78846-conflict-when-starting-3rd-times-a-job).

I would suggest to add such a constraint to the SQL scripts. For MySQL this could be:

```
ALTER TABLE BATCH_JOB_EXECUTION ADD UNIQUE job_instance_id_create_time_unique (JOB_INSTANCE_ID, CREATE_TIME);
```

---
No further details from [BATCH-2120](https://jira.spring.io/browse/BATCH-2120?redirect=false)

**Comment by fmbenhassine** [comment]
> That said, I think the unique constraint should be added for JOB_INSTANCE_ID, to enforce data consistency at the job repository level.

I seem to have overlooked the failure scenario in my previous comment. Adding a unique constraint on `JOB_INSTANCE_ID` is not correct: the `BATCH_JOB_EXECUTION` table can contain multiple records (ie job executions) for the same job instance ID (which is by design as a job instance might have multiple executions, for the failure/restart case for instance). Adding a unique constraint on `JOB_INSTANCE_ID` would prevent that, which is not the goal in the first place.
