### ISSUE TITLE
BatchStatus#isRunning() is not consistent with JobExplorer#findRunningJobExecutions(String) or JobExecution#isRunning()

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1483]
**[Alexis SOUMAGNE](https://jira.spring.io/secure/ViewProfile.jspa?name=almex)** opened **[BATCH-2114](https://jira.spring.io/browse/BATCH-2114?redirect=false)** and commented

In STOPPING status should be considered as a "running" status.
The endTime is null until job status is STOPPED. Which means that the job did not recieved interuption signal yet.

Simply the code should be :

```java
public boolean isRunning() {
   return this == STARTING || this == STARTED || this == STOPPING;
}
```

---

**Affects:** 2.2.2

**Comment by lcmarvin** [comment]
I also encountered a problem related to this issue. That is, when launching multi jobs with same parameters in multi threads, there should be only one job can succeed, but actually, there would be more than one job can succeed. I created a test [here](https://github.com/lcmarvin/spring-batch/blob/BATCH-1483/spring-batch-core/src/test/java/org/springframework/batch/core/launch/SimpleJobLauncherIntegrationTests.java).

I find it is caused by SimpleJobRepository#createJobExecution, this method uses `JobExecution#isRunning()`, but not BatchStatus#isRunning(). So the status STARTING is missing, since `startTime` of JobExecution will be set only when its status changes to STARTED.  
```
for (JobExecution execution : executions) {
    if (execution.isRunning() || execution.isStopping()) {
        throw new JobExecutionAlreadyRunningException("A job execution for this job is already running: " + jobInstance);
    }
...
```
