### ISSUE TITLE
Provide JobParametersIncrementer implementation based on a database sequence [BATCH-2074]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1521]
**[Gregory D. Hopkins](https://jira.spring.io/secure/ViewProfile.jspa?name=greg.hopkins)** opened **[BATCH-2074](https://jira.spring.io/browse/BATCH-2074?redirect=false)** and commented

Due to problems listed in the linked StackOverflow Q, I created an implementation of `org.springframework.batch.core.JobParametersIncrementer` based on Spring JDBC's `org.springframework.jdbc.support.incrementer.DataFieldMaxValueIncrementer`.

It looks like `org.springframework.jdbc.support.incrementer.DataFieldMaxValueIncrementer` is used several places in the Spring Batch project, but I could not find any that provided linkage to `org.springframework.batch.core.JobParametersIncrementer`.

Hopefully, others will find this useful.

---

**Reference URL:** http://stackoverflow.com/questions/17975917/spring-batch-runidincrementer-not-generating-next-value

**Attachments:**
- [DataFieldMaxValueIncrementerJobParametersIncrementer.java](https://jira.spring.io/secure/attachment/21311/DataFieldMaxValueIncrementerJobParametersIncrementer.java) (_1.21 kB_)

1 votes, 4 watchers

**Comment by benas** [comment]
I polished the attached file and added a test (see a333c164597785c776bd8bc6418790ba0eb3e091).

For future reference, here is a summary of the cases where the new `DataFieldMaxValueJobParametersIncrementer` has an added value compared to the `RunIdIncrementer`:

### 1. Un-ordered database sequences

Some database providers do not guarantee the order of numbers generated by sequences (like Oracle where [NOORDER](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/CREATE-SEQUENCE.html#GUID-E9C78A8C-615A-4757-B2A8-5E6EFB130571__GUID-215CB26D-89A2-4668-886C-59C4E05784B1) is the default). This means job instance IDs generated by `BATCH_JOB_SEQ` might not be in order. However, Spring Batch assumes that the last instance is the one with the highest ID. In this case, the incrementer might return the `run.id` of a previously completed instance (mistakenly leading to `JobInstanceAlreadyCompleteException`). Here is an example:

| Job instance | 1 | 22 | 23 | 2 | 3 |
| --- | --- | --- | --- | --- | --- |
| run.id | 1 | 2 | 3 | 4 | 4 |

In this example, when creating the job instance 2, Spring Batch will calculate the last instance (ie 23) and pass its `run.id` (which is 3) to the incremnter, which in turn returns 4. The same thing happens when creating job instance 3 (the max is always 23 here) and the incrementer will also return 4 leading to a `JobInstanceAlreadyCompleteException` at the time of launching the job. The new incrementer would return a different value thanks to the underlying `DataFieldMaxValueIncrementer`.

### 2. Concurrent access to the incrementer

The job parameters incrementer might be called concurrently when:

* Multiple threads call `JobOperator#startNextInstance` at the same time 
* Multiple processes call `CommandLineJobRunner` with `-next` option at the same time 

In these cases, those threads/processes might end-up with the same set of next parameters returned by the incrementer (since they might calculate the same last instance and pass its parameters to the incrementer). This leads to a `JobExecutionAlreadyRunningException` being thrown by the threads/processes that were not able to create the job instance (only one of them will succeed, others will fail). Since most `DataFieldMaxValueIncrementer` implementations are [thread-safe](https://github.com/spring-projects/spring-framework/blob/master/spring-jdbc/src/main/java/org/springframework/jdbc/support/incrementer/AbstractIdentityColumnMaxValueIncrementer.java#L84), the new incrementer should guarantee the uniqueness of generated values (and even if the implementation is not thread-safe, this should be guaranteed at the database level).
