### ISSUE TITLE
Dead Lock - ORA-00060 [BATCH-1990]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1602]
**[Muhammad Waqas Khalid](https://jira.spring.io/secure/ViewProfile.jspa?name=waqaskhalid)** opened **[BATCH-1990](https://jira.spring.io/browse/BATCH-1990?redirect=false)** and commented

Hi,

Our application is have deadlock exceptions while we are trying to process transactions using a thread count of 3.

Following is the trace of the exception.
at org.springframework.batch.core.step.item.FaultTolerantChunkProcessor$1.doWithRetry(FaultTolerantChunkProcessor.java:228)
at org.springframework.batch.retry.support.RetryTemplate.doExecute(RetryTemplate.java:240)
at org.springframework.batch.retry.support.RetryTemplate.execute(RetryTemplate.java:187)
at org.springframework.batch.core.step.item.BatchRetryTemplate.execute(BatchRetryTemplate.java:213)

We have reviewed the partition logic of the records at application level. It seems to be okay,However from the application logs it seems dead lock is caused by the same thread and trace only shows its coming while retrying.Can anyone help me in this regards.

Regards,
--Waqas

---

**Affects:** 2.1.8

**Comment by benas** [comment]
It's hard to see from what was shared what could the root cause be. Based on the issue creation date and affect version, I believe this is outdated. If you are still facing the problem with Spring Batch 4, feel free to re-open this issue (in which case, please provide a minimal complete example to reproduce it).

>  each thread process the data and update it in database using processor

An `ItemWriter` is more appropriate for database updates BTW.
