### ISSUE TITLE
Allow log file location to depend on Job context (e.g. job name) [BATCH-1704]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1882]
**[Dave Syer](https://jira.spring.io/secure/ViewProfile.jspa?name=david_syer)** opened **[BATCH-1704](https://jira.spring.io/browse/BATCH-1704?redirect=false)** and commented

Clearly this depends on the output log framework, so we will probably not be trying to cover them all. Log4J seems like the obvious choice to support since there is some Spring support for that already.

---

**Issue Links:**
- [XD-2492](https://jira.spring.io/browse/XD-2492) Increase Exit Description Text field on Job Execution Process step page

1 votes, 7 watchers

**Comment by fmbenhassine** [comment]
I don't see how we can support that in the framework itself. The reason is that Spring Batch does not create or manage threads directly. All concurrency features (multi-threaded steps, partitioned steps, asynchronous processing, etc) are based on task executors. Levering MDC support in logging libraries is the best (and probably only) option in my opinion.
