### ISSUE TITLE
Pull gridSize from job parameters [BATCH-1612]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1972]
**[Stéphane Nicoll](https://jira.spring.io/secure/ViewProfile.jspa?name=snicoll)** opened **[BATCH-1612](https://jira.spring.io/browse/BATCH-1612?redirect=false)** and commented

I would like to be able to customize the grid size of a given partition using the job parameters. Right now, I can customize the commit-interval (see [BATCH-541](https://jira.spring.io/browse/BATCH-541)) but I haven't found a way to do the same for the partition.

Thanks.

---

**Affects:** 2.1.1

**Issue Links:**
- [BATCH-1846](https://jira.spring.io/browse/BATCH-1846) late binding of partition grid-size within <handler.../>
 (_**"is duplicated by"**_)

**Comment by benas** [comment]
This seems outdated. With Spring Batch 4, there are at least two ways to pull the grid size from job parameters:

* Using a step-scoped partition handler, as mentioned in the previous [comment](https://github.com/spring-projects/spring-batch/issues/1972#issuecomment-566288731)
* Using a job-scoped master step, as shown int the following example:

```java
@Bean
@JobScope
public Step masterStep(@Value("#{jobParameters['gridSize']}") Integer gridSize) {
	return stepBuilderFactory("masterStep")
			.partitioner(workerStep().getName(), partitioner())
			.step(workerStep())
			.gridSize(gridSize)
			.taskExecutor(new SimpleAsyncTaskExecutor())
			.build();
}
```

This this issue was opened against v2.1.1 (before introducing the `JobScope` in v3), I believe it is outdated.

I'm closing this issue for now, but feel free to re-open it if necessary.
