### ISSUE TITLE
Asynchronous JobRepository [BATCH-1524]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#2058]
**[Dave Syer](https://jira.spring.io/secure/ViewProfile.jspa?name=david_syer)** opened **[BATCH-1524](https://jira.spring.io/browse/BATCH-1524?redirect=false)** and commented

Asynchronous JobRepository.  The range of environments that Batch can run in is limited by the central shared database, and the need for serialized synchronous access to the JobRepository.  To open up new possibilities (e.g. cloud bursting) we would need an asynchronous message-driven pattern so that updates to the repository can be scheduled without having to wait for them to be co-ordinated.  The goal is "eventual consistency" of the repository.

---

1 votes, 1 watchers

**Comment by fmbenhassine** [comment]
> The goal is "eventual consistency" of the repository.

"eventual consistency" of the repository means "eventual restartability", which does not feel as a wanted feature for batch environments. As a batch user, I would either design my job to be restartable without relying on a job repository at all, or design restartability based on a reliable job repository (not an eventually consistent job repository, otherwise restartability is not guaranteed).
