### ISSUE TITLE
Meta-annotate @SpringBatchTest with @ExtendWith(SpringExtension.class)

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-batch#3647]
Similar to how many Spring Boot test annotations are meta-annotated with `@ExtendWith(SpringExtension.class)` -- for example, `@SpringBootTest`, `@WebMvcTest`, etc.) -- I recommend that `@SpringBatchTest` be meta-annotated with `@ExtendWith(SpringExtension.class)` in order to simplify configuration when writing tests with JUnit Jupiter.

**Comment by dimitrisli** [comment]
@benas could I pick this one up? The @ExtendWith() will require junit-jupiter-api dependency, is that ok?

**Comment by benas** [comment]
@dimitrisli I have already a branch for that: https://github.com/benas/spring-batch/tree/GH-3647 (See https://github.com/benas/spring-batch/commit/2fc8f6e66e9fb119a93e406c2f779b0c3dc594d0). I just did not open a PR yet. But if you want to do it, go ahead you are welcome!

**Comment by benas** [comment]
Since github added the ability to create draft PRs recently, I created a draft PR for this here: https://github.com/spring-projects/spring-batch/pull/3697.

> But if you want to do it, go ahead you are welcome!

@dimitrisli I created the draft PR to avoid duplicate efforts, but feel free to review or test the change. Any contribution is welcome! Thank you upfront.

**Comment by dimitrisli** [comment]
@benas no problem at all, please do continue on this
