### ISSUE TITLE
Preventing Multiple Batch Job Executions running at same time and limit to only 1

### ISSUE THREAD

**Issue by MithuMohan** [spring-projects/spring-batch#3671]
Have a Spring Batch application that is scheduled to run at a certain time of day. There are 2 container instances running the application but we want to limit the job run to one instance only at a given time.
The tables show that some times multilple job execution entries are getting created for a single job instance  entry in spring batch table. How can we prevent this?
Spring Batch version used is 4.1.2

Have this snippet of code to prevent the second job from running. Does not work always.

private boolean isJobRunning(Job job) {
    Set<JobExecution> jobExecutions = jobExplorer.findRunningJobExecutions(job.getName());
    LOGGER.info("Searching for Job {} and Total Running Jobs are {}", jobExecutions.size());
    return !jobExecutions.isEmpty();
  }

  // run at 3am one time
  @Scheduled(cron = "1 am daily")
  public void runJob() {
  try {
      if (isJobRunning(myJob)) {
        LOGGER.info("#myJob Already Initiated, so Return");
        return;
      } else {
         JobParametersBuilder jobParametersBuilder = new JobParametersBuilder();
        jobParametersBuilder.addString("date",
            LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd-HH-mm")));

        JobParameters jobParameters = jobParametersBuilder.toJobParameters();

        JobExecution execution = jobLauncher.run(myJob, jobParameters);
      }
    } catch (Exception e) {
}

The Isolation Level for Job Create is Read_Uncommitted. The other levels result in  more duplicate jobs running at same time.

What configuration are we missing here , which will ensure no 2 jobs will execute at same time.

**Comment by benas** [comment]
This is better asked on stack overflow, here is a similar question: [Activate Batch on only one Server instance](https://stackoverflow.com/questions/60216411/activate-batch-on-only-one-server-instance). But I will answer the question here then close the ticket.

One of the goals of the job repository is to act as a safeguard against duplicate job executions in a clustered environment. So by design, one app instance will be able to create a job execution and the other will fail, here is an excerpt from the [Javadoc of `JobRepository`](https://docs.spring.io/spring-batch/docs/4.2.x/api/org/springframework/batch/core/repository/JobRepository.html#createJobExecution-java.lang.String-org.springframework.batch.core.JobParameters-):

```
The first transaction to complete in this scenario obtains a valid JobExecution, 
and others throw JobExecutionAlreadyRunningException (or timeout)
```

IMO there is no need to write code to prevent this failure, since we know upfront that it might happen by design, so it can be ignored.

> The Isolation Level for Job Create is Read_Uncommitted. The other levels result in more duplicate jobs running at same time.

You did not mention what other levels you have tried (weaker than  `Read_Uncommitted` or stronger). If `Read_Uncommitted` does not work for you, use a more aggressive value like `SERIALIZABLE`.
