### ISSUE TITLE
Deprecate MultiResourceItemReader#getCurrentResource

### ISSUE THREAD

**Issue by benas** [spring-projects/spring-batch#3776]
According to Robert. K, `MultiResourceItemReader#getCurrentResource` was [never meant to be public and is an accidentally leaked implementation detail](https://github.com/spring-projects/spring-batch/issues/1758#issuecomment-566286052). Dr D. Syer [never liked that getter](https://github.com/spring-projects/spring-batch/issues/1758#issuecomment-566286038).

I agree with both of them, this getter is confusing because in order to use it, one needs to inject the item reader in the item processor or line mapper to get the current resource (which is obviously a bad design as it couples batch artefacts), here are a few examples:

* https://stackoverflow.com/questions/63387024/how-to-get-current-resource-name
* https://stackoverflow.com/questions/43097612/accessing-name-of-flat-file-from-flatfileitemreader-linemapper/43098630#43098630
* https://stackoverflow.com/questions/22993633/get-current-resource-name-using-multiresourceitemreader-spring-batch

The correct way to get the current resource is by using the [ResourceAware](https://docs.spring.io/spring-batch/docs/4.2.x/api/org/springframework/batch/item/ResourceAware.html) interface which was typically designed for this use case, here is an excerpt from its Javadoc:

```
Marker interface indicating that an item should have the Spring Resource in which it was read from, set on it.
The canonical example is within MultiResourceItemReader, which will set the current resource on any items
that implement this interface.
```

**Comment by tomgeraghty3** [comment]
@benas  I have a use case that I'm trying to migrate to using `ResourceAware` instead but am getting stuck. Current setup:
- A `MultiResourceItemReader` that uses a `FlatFileItemReader` delegate
- The `FlatFileItemReader` utilises a `LineCallbackHandler` via the `skippedLinesCallback()` method
- Currently the `LineCallbackHandler` has the `MultiResourceItemReader` injected so that in the `handleLine(String line)` I can log/use the name of the current file that is being processed e.g. `String fileIdentifier = itemReader.getCurrentResource().getDescription()`
- As far as I understand your _Item_ domain class can implement `ResourceAware` instead of using this getter but in my case I don't have an _Item_ domain class yet... I just have the input String from the file because the line has been skipped

How would I go about making my `LineCallbackHandler` "resource aware" so that I can continue with the logic I have just now?

**Comment by benas** [comment]
@tomgeraghty3 To get help for questions like this one, please use stack overflow (see [getting help](https://github.com/spring-projects/spring-batch#getting-help)). Thank you for your comprehension.

**Comment by tomgeraghty3** [comment]
@benas Yeah that makes more sense sorry posted it there thanks - https://stackoverflow.com/questions/66908987/resourceaware-instead-of-multiresourceitemreader-getcurrentresource-for-lineca
