### ISSUE TITLE
ScripItemProcessor python implementation

### ISSUE THREAD

**Issue by EdgardHernandezp** [spring-projects/spring-batch#3875]
I wanted to use a web scraping python script in my batch program but this is not feasible in Spring Batch. I want to request for this feature in a future Spring version. Python grows in popularity and using a python script with ScriptItemProcessor I think is becoming a necessity.

**Comment by benas** [comment]
Thank you for opening this issue. The `ScriptItemProcessor` delegates item processing to a `ScriptEvaluator` which is from Spring Framework. As of v5.3, Spring Framework provides three implementations of the `ScriptEvaluator` interface: `BshScriptEvaluator`, `GroovyScriptEvaluator` and `StandardScriptEvaluator`.

By default, if you don't specify which `ScriptEvaluator` to use, the `ScriptItemProcessor` will use a `StandardScriptEvaluator`, see Javadoc of [setScriptEvaluator](https://docs.spring.io/spring-batch/docs/4.3.x/api/org/springframework/batch/item/support/ScriptItemProcessor.html#setScriptEvaluator-org.springframework.scripting.ScriptEvaluator-). Now this [StandardScriptEvaluator](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/scripting/ScriptEvaluator.html) is based on JSR-223 `javax.script`, so you need to make sure the language you want to use is supported by the default `ScriptEngine`. Python is not a supported language by default. If you want to use Python through JSR-223 with the `StandardScriptEvaluator`, you can use [Jython](https://www.jython.org) (Adding the jar of `Jython` to the classpath should be enough, see the [Using JSR 233](https://wiki.python.org/jython/UserGuide#using-jsr-223) section from Jython docs).

I'm closing this issue since there is nothing to do in Spring Batch.

---

Reference: https://stackoverflow.com/questions/66818971/spring-batch-scriptitemprocessor (which I answered on SO)
