### ISSUE TITLE
spring-boot upgrade from 2.2.0 -> 2.2.1 breaks spring-batch persistance to database  (or any spring boot > 2.2.0)

### ISSUE THREAD

**Issue by alpizano** [spring-projects/spring-batch#3887]
Hi, I posted before but my issue closed. I have a  (somewhat) simple spring boot/spring batch application that loads files from a .CSV and transforms/maps that data  and persists to a Postgresql database. It was running perfectly fine on spring-boot-starter 1.5.9.RELEASE. However, upon upgrading to anything > 2.2.0 spring-boot-starter, I noticed the any repository calls to the database (postgres) will not work. The application will be in a "Running" state on port 8080, but it will hang/freeze/stick on the JpaRepository method, in this case, I am using the `.saveAll()` for my entity.

The interesting thing is both 2.2.0 and 2.2.1 use spring-batch-core 4.2.0.RELEASE. 

Another objective for myself was to try and get on spring-batch-core 4.3.2.RELEASE, which was a problem , since I could only get to spring-batch-starter 2.2.0 as started above. However, I was able to manually <exclusion>spring-batch-core</exclusion> from the spring-batch-starter and manually import 4.3.2.RELEASE, even though it failed, however I found a stackoverflow post stating there was a dependency on jackson-databind 2.11.0 (spring 2.2.0 uses 2.10.0):
https://stackoverflow.com/questions/65607909/spring-batch-2-4-1-wildfly-20-final-java-lang-nosuchfielderror-block-unsafe/65795467#65795467

Luckily this worked. I'm still perplexed why 2.2.1 is failing to persist for my spring batch application. Are there any advices I could get how to debug this?

**Comment by benas** [comment]
> spring-boot upgrade from 2.2.0 -> 2.2.1 breaks spring-batch persistance to database (or any spring boot > 2.2.0)

> The interesting thing is both 2.2.0 and 2.2.1 use spring-batch-core 4.2.0.RELEASE.

Since the version of Spring Batch is the same and it works with boot 2.2.0 but not with boot 2.2.1, I don't understand why this issue is opened against Spring Batch and not against Spring Boot. As mentioned [previously by myself](https://github.com/spring-projects/spring-batch/issues/3885#issuecomment-819462226) (and by the [boot team](https://github.com/spring-projects/spring-boot/issues/25989#issuecomment-816834738)), please use StackOverflow for this kind of questions. If you provide a minimal complete example that we can use to reproduce the issue and validate that there is a bug, then we can open an issue here.

Thank you for your comprehension and for your collaboration.
