### ISSUE TITLE
documentation : example for in-memory repository, with no deprecated classes

### ISSUE THREAD

**Issue by vincent-fuchs** [spring-projects/spring-batch#4016]
The current example provided in the documentation to run a job with an in-memory repository actually uses `MapJobRepositoryFactoryBean`, which is deprecated. 

https://docs.spring.io/spring-batch/docs/current/reference/html/index-single.html#inMemoryRepository 

It would be good to review the example and provide one that shows the "real" recommended way.. I guess it would be way to use an H2 datasource (ideally, programmatically) initialized with the proper tables so that it can be used directly

**Comment by benas** [comment]
This is similar to #3834, where I mentioned that the suggested replacement can be found in the Javadocs. There is also a first draft of a [migration guide](https://github.com/spring-projects/spring-batch/wiki/Spring-Batch-5.0-Migration-Guide#job-repositoryexplorer-configuration-updates) for v5.

But since this is a recurring request, I think the reference documentation should also be updated with a deprecation note and a sample.

**Comment by benas** [comment]
Resolved with 9deaa16.
