### ISSUE TITLE
Spring Batch Remote Chunking Manager Recovery Process

### ISSUE THREAD

**Issue by akashsharma3030** [spring-projects/spring-batch#4298]
**Expected Behavior**

Spring Batch Remote Chunking Manager should be able to recover from JVM crash or restart of the application for executing existing job.

**Current Behavior**

Currently the Spring Batch Remote Chunking Manager Job cannot recover when Jvm crash or application gets restarted for existing jobs.

**Context**
We have requirement to make the Spring Batch Remote Chunking Highly available and If Spring Batch remote Chunking Manager goes down then either another Manager should take over or existing Manager instance after restart should continue processing existing job.

Currently only workaround is to manually marked the job as failed and start the fresh job

**Comment by fmbenhassine** [comment]
Does the manager's JVM crash gracefully or abruptly? What is the status of the job in the repository when that happens?

If the job fails gracefully, it should resume where it left off when you restart it.

If it fails abruptly, you have to change its state to FAILED and restart it. In this case, it should resume where it left off as well.

**Comment by akashsharma3030** [comment]
Hi @fmbenhassine ,


Thanks for your quick reply.
I didn't know that I could restart the failed job that will help alot.
If JVM crashes the status of the job is Started.

Also another question we wanted to have two instances of RemoteChunking Manager. So If one worker crashes   the other worker could take it over do you see any possibilities or any suggestion regarding the same. Here the question is how would another Manager know if the other worker is down.

Regards,
Akash Sharma

**Comment by fmbenhassine** [comment]
> If JVM crashes the status of the job is Started.

If the job is in the `STARTED` status, it means that the JVM crashed abruptly and Spring Batch did not have a chance to update the job's status to `FAILED`. A graceful shutdown would change the job's status to `FAILED` and it will be possible to restart it (and it will restart from where it left off). In your case, if you know that the job could be restarted, then you have to update the status manually and restart it (of course restart the same job instance). There is a mention about this in the documentation: [Aborting a Job](https://docs.spring.io/spring-batch/docs/current/reference/html/job.html#aborting-a-job).

So what you say here: "Currently only workaround is to manually marked the job as failed and start the fresh job" is not a workaround, but the way you should proceed by design. When Spring Batch runs a job, it cannot (by just looking at a `STARTED` status) distinguish between a currently running job and a job that was killed abruptly. Hence, it is up to you to to decide if the job has effectively failed or should be aborted.

Now if the job fails gracefully (ie its status ends up as `FAILED`) but cannot recover from the failure and resume where it left off when restarted, then that could be a bug in Spring Batch. If that is the case for you, please provide a minimal example that reproduces the issue and we will dig deeper.

> Also another question we wanted to have two instances of Remote Chunking Manager.

That is not possible by design. You can have multiple workers, but only a single manager.

**Comment by fmbenhassine** [comment]
As mentioned previously, changing the status manually in the database is the way to recover from an abrupt shutdown.
