### ISSUE TITLE
Spring Batch does not initialize metadata tables when property initialize-schema: always is set

### ISSUE THREAD

**Issue by mbrzez** [spring-projects/spring-batch#4306]
**Bug description**
Spring Batch does not initialize its [metadata tables](https://docs.spring.io/spring-batch/docs/current/reference/html/schema-appendix.html) when annotation `@EnableBatchProcessing` and the property `initialize-schema: always` is set. When running simple job test [SpringBatchConfigTest](https://github.com/mbrzez/spring-batch-init-db-tables/blob/main/src/test/java/pl/brzezins/app/batch/SpringBatchConfigTest.java) test I got

`Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "BATCH_JOB_INSTANCE" not found (this database is empty)`

This issue seems not to happen when using spring-boot-starter-batch:2.7.8 and corresponding spring-batch-core:4.3.7

**Environment**
* Local
* H2 in-memory database

**Dependencies**
* spring-boot-starter 3.0.2
* spring-boot-starter-batch 3.0.2
* spring-batch-core 5.0.0

**Steps to reproduce**
Run [SpringBatchConfigTest](https://github.com/mbrzez/spring-batch-init-db-tables/blob/main/src/test/java/pl/brzezins/app/batch/SpringBatchConfigTest.java) test

**Expected behavior**
I expect Spring Batch to initialize metadata tables when `@EnableBatchProcessing` annotation and `initialize-schema: always` property and is set. A [SpringBatchConfigTest](https://github.com/mbrzez/spring-batch-init-db-tables/blob/main/src/test/java/pl/brzezins/app/batch/SpringBatchConfigTest.java) test should pass.

**Minimal Complete Reproducible example**
Please see: https://github.com/mbrzez/spring-batch-init-db-tables

**Comment by fmbenhassine** [comment]
This is because you are using `@EnableBatchProcessing`, which is not needed anymore with Spring Boot 3, see migration guide here: [Spring Batch Changes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#spring-batch-changes). Please check the [migration guide of Spring Batch 5](https://github.com/spring-projects/spring-batch/wiki/Spring-Batch-5.0-Migration-Guide) as well.

When I remove [@EnableBatchProcessing](https://github.com/mbrzez/spring-batch-init-db-tables/blob/main/src/main/java/pl/brzezins/app/batch/SpringBatchConfig.java#L15) from your sample, the mentioned test passes without any exception.

I am closing this issue for now, but if you need help migrating your Spring Batch app to v5, do not hesitate to add a comment here or ask a question on StackOverflow.
