### ISSUE TITLE
Incorrect v5 migration script for SQLServer

### ISSUE THREAD

**Issue by iyerha** [spring-projects/spring-batch#4349]
**Bug description**
The migration script for sqlserver provided in spring-batch-core for version 5.0 is incorrect.

**Environment**
Spring Batch version: 5.0.1, Java version = 17.0.6_10, database=SQLServer 2019

**Steps to reproduce**
All bugs relate to the table BATCH_JOB_EXECUTION_PARAMS in migration-sqlserver.sql script under 5.0:
1. You cannot drop column DATE_VAL without first dropping the default constraint on it.
2. You cannot use MODIFY COLUMN to rename columns (TYPE_CD, KEY_NAME, STRING_VAL). You would need to use the sp_rename procedure as described [here](https://learn.microsoft.com/en-us/sql/relational-databases/tables/rename-columns-database-engine?view=sql-server-ver15)

**Comment by fmbenhassine** [comment]
Thank you for raising this. This is similar to another issue we had with PostgreSQL and Oracle. The SQL syntax is not the same for each database, which was assumed when creating the migration scripts.. I created an issue to improve the testing process for next releases, see https://github.com/spring-projects/spring-batch/issues/4289.

I will plan the fix for the next release. You are welcome to contribute if you managed to correctly migrate your schema to v5 on SQLServer.
