### ISSUE TITLE
Include read, write, skip etc. counters in metrics

### ISSUE THREAD

**Issue by mdeinum** [spring-projects/spring-batch#4385]
Currently the usage of the Metrics is limited to some Spring Batch metadata (jobs, steps) and the time it took a step to execute. It would be nice if this could be extended with counters for the counters available on the `StepContribution`.

**Comment by fmbenhassine** [comment]
Spring Batch [already](https://docs.spring.io/spring-batch/docs/current/reference/html/monitoring-and-metrics.html#built-in-metrics) publishes metrics from the `StepContribution` for item reading, writing, etc (and not only jobs and steps). However, they are of type timer and not counter, and the reason is the following:

When we first introduced Micrometer metrics in Spring Batch, we had a discussion with the observability team about adding those counters. The rule of thumb we got is to "Never count something you can time with a Timer", as timers also publish the operation count as well. Here is an excerpt from Micrometer's [docs](https://micrometer.io/docs/concepts#_counters):

```
Never count something you can time with a Timer or summarize with a DistributionSummary! Both Timer and DistributionSummary always publish a count of events in addition to other measurements.
```

That is the reason we use timers for metrics like `item.read`, `item.process`, etc which give both the timing of the operation as well as counts. Here is an example of the `spring.batch.item.read` Meter you would get from Micrometer:

```
COUNT | value = 5.0
TOTAL_TIME | value = 0.003753161
MAX | value = 0.003618066
```

So you should be able to get the counters already from the built-in metrics published by Spring Batch. Is that what you are looking for?

**Comment by fmbenhassine** [comment]
Closing this based on the reaction to my last comment.
