### ISSUE TITLE
Documentation unclear on how to replace deprecated AbstractTaskletStepBuilder#throttleLimit

### ISSUE THREAD

**Issue by vaclavsvejcar** [spring-projects/spring-batch#4389]
Hello,

I have question about the `AbstractTaskletStepBuilder#throttleLimit`. JavaDoc says that:

```
since 5.0, scheduled for removal in 6.0. Use a pooled TaskExecutor implementation with a limited capacity of its task queue instead.
```

But it's IMHO not obvious how this should be replaced and even official documentation still uses this method (https://docs.spring.io/spring-batch/docs/current/reference/html/scalability.html)

This is the snippet of the code we're using right now

```java
        final int numberOfThreads = 32;
        ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
        executor.setCorePoolSize(numberOfThreads);
        executor.setPrestartAllCoreThreads(true);
        executor.afterPropertiesSet();

....
        
        return new StepBuilder("someName", jobRepository)
                .<ProcessDocumentRequest, ProcessDocumentResponse>chunk(chunkSize, transactionManager)
                .reader(synchronizedItemStreamReader())
                .processor(itemProcessor())
                .writer(documentWriter())
                .taskExecutor(delegatingSecurityContextAsyncTaskExecutor(executor))
                .throttleLimit(numberOfThreads)
                .build();
```

But it seems when we remove the `.throttleLimit` it only runs in 4 threads, which seems to be the default value defined in `AbstractTaskletStepBuilder` by

```java
private int throttleLimit = TaskExecutorRepeatTemplate.DEFAULT_THROTTLE_LIMIT;
```

Can you please clarify how to set up the task executor so it works in the same way as when using the `throttleLimit` method?

**Comment by fmbenhassine** [comment]
Thank you for opening this issue. I must admit this is confusing, that's why we are planning to review the concurrency model completely (see #3950).

The issue is that even if one provides a pooled task executor as stated by the javadoc, the `TaskExecutorRepeatTemplate` will still be used and will be capped at that default throttle limit of 4, and there is no way to override that default without calling the, now deprecated, `throttleLimit` method.. 

The correct way to replace that deprecation is actually to go one level up (ie above the `TaskExecutor`), meaning by using a custom `RepeatOperations` through `AbstractTaskletStepBuilder#stepOperations`. This way, `TaskExecutorRepeatTemplate` won't be used and that method won't need to be called. We will update the javadocs and reference docs accordingly.

**Comment by RT-1904129** [comment]
Hi @fmbenhassine 
Can you provide sample hints or example to help me to resolve this issue ?????
