### ISSUE TITLE
Regression with the css styles and toggle in the reference documentation of 4.3.x

### ISSUE THREAD

**Issue by fmbenhassine** [spring-projects/spring-batch#4437]
There seems to be a regression with the css styles in the reference documentation of 4.3.x: https://docs.spring.io/spring-batch/docs/4.3.9/reference/html/

This is probably related to switching to `spring-asciidoctor-backends`: https://github.com/spring-projects/spring-batch/commit/af61a396ffb9244df283f7a9424f2597b2df7dd0

@Buzzardo Could you please take a look? Thank you upfront.

**Comment by Buzzardo** [comment]
I took a look and don't see a problem. What are you seeing that's wrong?

**Comment by fmbenhassine** [comment]
Compared to the 4.3.8 version, the spring styles (the banner at the top of the page, the background colour of code blocks, etc) are not rendered:

https://docs.spring.io/spring-batch/docs/4.3.8/reference/html/

https://docs.spring.io/spring-batch/docs/4.3.9/reference/html/

**Comment by Buzzardo** [comment]
I built 4.3.x, and it came out correctly. I noticed that it built 4.3.10. When I tried to build 4.3.9, I got a bunch of repository issues, due to the changes of a few months ago that we made to which Spring repositories are available. I think we should ignore 4.3.9 and accept that it's correct in 4.3.10.
