### ISSUE TITLE
Problem of continuing to use previous settings even if job parameters are not set

### ISSUE THREAD

**Issue by sangbinlee** [spring-projects/spring-batch#4466]
Please do a quick search on Github issues first, there might be already a duplicate issue for the one you are about to create.
If the bug is trivial, just go ahead and create the issue. Otherwise, please take a few moments and fill in the following sections:

**Bug description**
You are great.
@Value("#{jobParameters[requestDate]}") String requestDate I would like to inquire what to do in the following cases.
test1. If you set the job parameter requestDate and execute the batch, the set parameter value can be confirmed (normally).
test2. I assumed that if the job parameter requestDate was not set, the parameter value would be null, but in reality, the parameter value used in the previous batch was set, so there is no way to distinguish between the case where the parameter was set and the case where the parameter was not set from the batch app's perspective. Is there any way to tell them apart?

**Environment**
Please provide as many details as possible: Spring Batch version, Java version, which database you use if any, etc

**Steps to reproduce**

@Value("#{jobParameters[requestDate]}") String requestDate I would like to inquire what to do in the following cases.
test1. If you set the job parameter requestDate and execute the batch, the set parameter value can be confirmed (normally).
test2. I assumed that if the job parameter requestDate was not set, the parameter value would be null, but in reality, the parameter value used in the previous batch was set, so there is no way to distinguish between the case where the parameter was set and the case where the parameter was not set from the batch app's perspective. Is there any way to tell them apart?

**Expected behavior**
 there is no way to distinguish between the case where the parameter was set and the case where the parameter was not set from the batch app's perspective. Is there any way to tell them apart?

**Minimal Complete Reproducible example**

![image](https://github.com/spring-projects/spring-batch/assets/4024414/d8128fb3-d772-4397-9700-0dffa1f2147a)

![image](https://github.com/spring-projects/spring-batch/assets/4024414/4096d6e7-8bdb-429c-81ee-e03f11c4bcf9)

![image](https://github.com/spring-projects/spring-batch/assets/4024414/6eefddfc-c386-437f-97ec-2f1625bbef55)

![image](https://github.com/spring-projects/spring-batch/assets/4024414/1375a040-5f5d-4637-bef1-6ddded93fdb1)

**Comment by fmbenhassine** [comment]
This is because you are using a job parameters incrementer. In this case, parameters from the previous execution are appended to the new ones, overriding any existing keys. This is explained in the Javadoc of [CommandLineJobRunner](https://docs.spring.io/spring-batch/docs/current/api/org/springframework/batch/core/launch/support/CommandLineJobRunner.html): 

```
If the -next option is used the parameters on the command line (if any) are *appended*
to those retrieved from the incrementer, *overriding any with the same key*.
```

Spring Boot (which you seem to be using) has also the same behaviour when you set an incrementer on the job.

So in your case, not using an incrementer is the way to go. An incrementer is really only useful when there is a clearly defined sequence of job instances based on job parameters (ie the next job instance is defined by incrementing the parameters of the previous job instance).

I am closing this issue as I believe I answered your question, but feel free to add a comment if you need more help on this.

Duplicates: #3683, #789.
