### ISSUE TITLE
Restarting a job after server crash is not processing the unprocessed data.

### ISSUE THREAD

**Issue by PSHREYASHOLLA** [spring-projects/spring-batch#4481]
Description and code is available at ,
https://stackoverflow.com/questions/77309170/how-to-make-the-jobregistry-contain-the-job-information-on-server-restart-in-spr/77325676?noredirect=1#comment136431441_77325676.

Solution is requested for below part,
now after restart a new Job execution starts and says completed but it fails to process the data. If the job runs on a single thread it processes all the data, but if its multi thread it does not do anything. Please check https://github.com/PSHREYASHOLLA/SamplebatchApplication/blob/main/src/main/java/com/example/postgresql/model/EmployeeTaxCalculationBatchConfig.java

Line 60, Step step = new StepBuilder("FEBP_EMP_TAX_CALCULATION_STEP", jobRepository) .<EmployeeDetail, EmployeeTaxDetail>chunk(5, transactionManager) .reader(reader.getPagingItemReader()).processor(itemProcessor).writer(itemWriter).taskExecutor(actStmntTaskExecutor()) .throttleLimit(50).build();

Here if throttleLimit is 1 it process records after restart, but if its multithreaded it does not process remaining records in my sample table.

**Comment by fmbenhassine** [comment]
This is not related to the server's restart, but rather to the throttle limit value (50) which should be lower than the pool size (also 50 in your example). This is mentioned in the [javadoc](https://docs.spring.io/spring-batch/docs/5.0.2/api/org/springframework/batch/repeat/support/TaskExecutorRepeatTemplate.html#setThrottleLimit(int)):

```
when used with a thread pooled TaskExecutor the thread pool might prevent the throttle limit actually being reached
(so make the core pool size larger than the throttle limit if possible).
```

I am closing this issue as I answered the question on SO. Please follow up there if you need more support (in that case, please open a different question because this is a completely different issue from the initial one).

**Comment by PSHREYASHOLLA** [comment]
Sure, Please check https://stackoverflow.com/questions/77432989/restarting-a-job-after-server-crash-is-not-processing-the-unprocessed-data?noredirect=1#comment136510660_77432989.
