### ISSUE TITLE
Use '@EnableBatchProcessing' carefully on Spring Boot3.

### ISSUE THREAD

**Issue by kang-seongbeom** [spring-projects/spring-batch#4605]
When using '@EnableBatchProcessing' in Spring Boot3, default settings are initialized. Therefore, batch operation may not work.

**Comment by fmbenhassine** [comment]
With Spring Boot 3, it is no longer required to use `@EnableBatchProcessing` to enable Spring Boot’s auto-configuration of Spring Batch. If you use that annotation, the auto-configuration of batch (including the automatic job execution at startup) will back-off. 

There is a section about this change in the migration guide of Spring Boot 3: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#spring-batch-changes . There is also a note as well in the getting started guide of Spring Batch: https://spring.io/guides/gs/batch-processing (See `Note how the application does not use the @EnableBatchProcessing annotation`..). Is this what you are looking for?

**Comment by kang-seongbeom** [comment]
That's right. I was able to remove @EnableBatchProcessing by looking at "https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#spring-batch-changes". However, there is no warning about back-off in "https://docs.spring.io/spring-batch/reference/job/java-config.html". Therefore, I added a cautionary note to “https://github.com/spring-projects/spring-batch/pull/4606”!

**Comment by fmbenhassine** [comment]
> However, there is no warning about back-off in "https://docs.spring.io/spring-batch/reference/job/java-config.html".

There is no such a note because this is a behaviour of Spring Boot. We do not document Spring Boot behaviour in Spring Batch docs. If you think docs can be improved, please open an issue or a PR on the boot side. I will close this issue and the corresponding PR, but As mentioned previously, there is a note about this in the migration guide of boot as well as the official docs: https://docs.spring.io/spring-boot/how-to/batch.html#howto.batch.specifying-a-data-source.

The only sample that uses Spring Boot on the batch side is the getting started guide, in which there is a note about that behaviour as well: https://spring.io/guides/gs/batch-processing (See `Note how the application does not use the @EnableBatchProcessing annotation`..).
