### ISSUE TITLE
Wrong column types in JdbcStepExecutionDao

### ISSUE THREAD

**Issue by v00d00c0de** [spring-projects/spring-batch#4648]
In 5.0, StepExecution's 'int' fields were updated to 'long'.
JdbcStepExecutionDao::buildStepExecutionParameters was changed accordingly to use Types.BIGINT for such fields, but not JdbcStepExecutionDao::updateStepExecution.

https://github.com/spring-projects/spring-batch/blob/425134c74e6b69dde40a81278e4fddbec4778f80/spring-batch-core/src/main/java/org/springframework/batch/core/repository/dao/JdbcStepExecutionDao.java#L280

**Comment by fmbenhassine** [comment]
That's correct, thank you for raising this!

The row mapper should also be updated to get values as `long` from the result set here: https://github.com/spring-projects/spring-batch/blob/0d1d89c82fc07194e8e36f11be9a0e164caf6333/spring-batch-core/src/main/java/org/springframework/batch/core/repository/dao/JdbcStepExecutionDao.java#L394

I will plan the fix for the next release.

**Comment by hyejinggu** [comment]
Is this issue still open for progress? I would like to know if I can go ahead and create a pull request to resolve it.

**Comment by fmbenhassine** [comment]
@hyejinggu You are welcome to contribute a PR. Thank you for your offer to help!
