### ISSUE TITLE
Rethink DefaultBatchConfiguration and/or update its doc

### ISSUE THREAD

**Issue by micheljung** [spring-projects/spring-batch#4650]
Hi, I think `DefaultBatchConfiguration`  has some issues that need to be addressed:

### The documentation suggests that it should be extended

Quote:

```
A typical usage of this class is as follows:

  @Configuration
  public class MyJobConfiguration extends DefaultBatchConfiguration {
 
      @Bean
      public Job job(JobRepository jobRepository) {
          return new JobBuilder("myJob", jobRepository)
                  // define job flow as needed
                  .build();
      }
 
  }
```

1. This suggests to extend `DefaultBatchConfiguration`. But following *Composition over Inheritance*, you would rather want to import it.
2. The only reason to extend `DefaultBatchConfiguration` should probably be to override e. g. `getTaskExecutor()`, allowing you to customize the Batch infrastructure. But then again, following *Composition over Inheritance*, it might be better to let the user provide a factory bean and/or a customizer.
3. While it already uses factory beans like `JobRepositoryFactoryBean`, these are hard coded and can neither be changed nor customized by the user.
4. The code above suggests defining job beans in your subclass of `DefaultBatchConfiguration`. This mixes two things that, IMO, should not be mixed: Batch infrastructure configuration and job configurations. What if you want to have multiple classes that define jobs, would you then extend `DefaultBatchConfiguration` multiple times? No, because if you do that, from which class will the beans be taken? Imagine overriding `getTaskExecutor()` in multiple subclasses: only one will win. So as a user, you most likely want to subclass `DefaultBatchConfiguration` at most once and put jobs into separate configs. Not everyone might realize this. Therefore, I think the doc shouldn't suggest mixing job config with infrastructure.

### It makes auto configuration difficult for Spring Boot

Even if customizable bean factories were provided, it would still not work well with Spring Boot AutoConfiguration where users expect beans to be replaceable. See https://github.com/spring-projects/spring-boot/issues/40040
If the suggested solution works, this point might be invalid. Still, maybe it's something to be considered.

I'm interested in reading your thoughts. When I find the time, I would also like to provide suggestions. Unfortunately, I can't right now.

**Comment by fmbenhassine** [comment]
Thank you for sharing your thoughts! I wish we had such great feedback when we worked on #3942 (which I recommend you to check if you want to understand the rationale behind the design choices in v5).

> 1. This suggests to extend DefaultBatchConfiguration. But following Composition over Inheritance, you would rather want to import it.
>2. The only reason to extend DefaultBatchConfiguration should probably be to override e. g. getTaskExecutor(), allowing you to customize the Batch infrastructure. But then again, following Composition over Inheritance, it might be better to let the user provide a factory bean and/or a customizer.

The idea of defining default infrastructure beans in a base class is not new, it is actually similar to several classes with same purpose across the portfolio (like [AbstractDispatcherServletInitializer](https://docs.spring.io/spring-framework/reference/web/webmvc/mvc-servlet/container-config.html) in Spring MVC and [AbstractSecurityWebApplicationInitializer](https://docs.spring.io/spring-security/reference/servlet/configuration/java.html#_abstractsecuritywebapplicationinitializer) in Spring Security). Composition over Inheritance really applies to business services in application code to make them swappable. In this context, we are actually writing some configuration code that we inherit from a base class and override if needed). That said, you can still `@Import` the default batch configuration class instead of extending it.

> 3. While it already uses factory beans like JobRepositoryFactoryBean, these are hard coded and can neither be changed nor customized by the user.

Factory beans should not be leaked in the API, otherwise this would be a design mistake IMHO. They are nothing more than nice to have components to ease the configuration of infrastructure beans. As a batch user, I should be able to define an infrastructure bean (a `JobRepository`for instance) and choose to use a factory bean or not.

> 4. The code above suggests defining job beans in your subclass of DefaultBatchConfiguration. This mixes two things that, IMO, should not be mixed: Batch infrastructure configuration and job configurations.

That's a fair point. I always recommend to separate infrastructure beans from business beans. A good example is the [hello world tutorial](https://github.com/spring-projects/spring-batch/blob/main/spring-batch-samples/src/main/java/org/springframework/batch/samples/helloworld/HelloWorldJobConfiguration.java), where infrastructure beans are defined in a separate class and imported in the job configuration class. The example you referred to can be refactored as such too, but one could argue that it is ok to inherit infrastructure beans from a base class (which is considered a separate class).

> It makes auto configuration difficult for Spring Boot

I understand and agree. This is a known limitation, I will add a comment on https://github.com/spring-projects/spring-boot/issues/40040 to mention that this is currently missing in Spring Boot. Currently, I can define a datasource and it will be picked up and set on the job repository (ie I don't have to redefine the job repository). In the same way, I should be able to define a task executor to use in the job launcher without having to redefine a job launcher.

Hopefully I answered all your questions.

**Comment by fmbenhassine** [comment]
> Case in point: I need to use `JsonJobParametersConverter` instead of `DefaultJobParametersConverter`. This is configured in `JobOperatorFactoryBean`. But in `DefaultBatchConfiguration`, the factory is hard coded and it doesn't call `setJobParametersConverter`.

This is a valid issue. Similar to the `ExecutionContextSerializer`, I should be able to define a bean of type `JobParametersConverter` and get it configured on top level infrastructure beans where appropriate. I will plan the addition in a minor release.

**Comment by fmbenhassine** [comment]
Hi @micheljung ,

I pushed a [commit](https://github.com/spring-projects/spring-batch/commit/461ae65f9e5ffcd96903b7f3a6bd2e00f85b0ae2) that allows you to define the job parameters converter without having to override the entire `DefaultBatchConfiguration#getJobOperator()` method. I also added the equivalent attribute in `@EnableBatchProcessing` for those who use the declarative configuration approach.

WRT to Spring Boot, I added a comment on https://github.com/spring-projects/spring-boot/issues/40040#issuecomment-2404751762 to introduce a new annotation that marks the task executor to use for Batch (which will allow to customize the task executor without having to define the job launcher). This will be available in Boot 3.5.

I believe I covered everything here, so I closed this issue as resolved. I will edit the title though to focus on new feature about the job parameters converter. Let me know if you need further support on this. Best regards.

**Comment by pPanda-beta** [comment]
Hi @fmbenhassine ,
Can we get something similar for the people who prefers to use auto configuration instead of `@EnableBatchProcessing` ?

I tried adding this
```kotlin
    @Bean
    fun jobParametersConverter(jacksonObjectMapper: ObjectMapper): JobParametersConverter {
        return JsonJobParametersConverter(jacksonObjectMapper)
    }

```

but it did not work because of auto configuration. 

class `BatchAutoConfigurationSpringBootBatchConfiguration` does not override `protected JobParametersConverter getJobParametersConverter()`

https://github.com/spring-projects/spring-boot/blob/4a2c26eeec751b409f614b20e374e0f21bc0f595/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/batch/BatchAutoConfiguration.java#L99

---

As workaround I had to add a converter specific to job parameter class

```kotlin
    @Bean
    fun customizer(jacksonObjectMapper: ObjectMapper) = BatchConversionServiceCustomizer { service ->
        service.addConverter(
            MySimpleDataClass::class.java, String::class.java, jacksonObjectMapper::writeValueAsString,
        )
        service.addConverter(String::class.java, MySimpleDataClass::class.java) { s ->
            jacksonObjectMapper.readValue(s, MySimpleDataClass::class.java)
        }
    }
```

But imagine if I have 20 data classes, `MySimpleDataClass`, `MySimpleDataClass2`, ... `MySimpleDataClass19`, I have to register them all (may be with a loop).

**Comment by pPanda-beta** [comment]
Thanks @fmbenhassine, I have opened https://github.com/spring-projects/spring-boot@fmbenhassine
