### ISSUE TITLE
Proper default value for skipLimit

### ISSUE THREAD

**Issue by samuelstein** [spring-projects/spring-batch#4661]
Recently I stumbled over the default value of the _skipLimit_ in the class _FaultTolerantStepBuilder_. It is set by default to 0. 
If you don't use a SkipPolicy and configure it instead with _skip(Exception.class)_ it is very easy to forget setting the additional property _skipLimit_.
Could you provide a more suitable default value? 
My suggestion would be _Integer.MAX_VALUE_.
What do you think?

**Comment by fmbenhassine** [comment]
That's a valid point, thank you for raising it!

> My suggestion would be _Integer.MAX_VALUE_

This means that by default we would theoretically allow the entire dataset to be skipped, which in turn means there is something fundamentally wrong with the input (bad data format, unexpected input, etc). As a user, I would prefer my job to fail fast in the first dozen or hundred skips rather than waiting untill the end just to discover that my job was skipping the entire data set. Do you see my point?

I guess 10 or 100 is a reasonable default. Wdyt?

I will plan the change in the next minor release.

**Comment by samuelstein** [comment]
Hi @fmbenhassine,
this makes abolutely sense to me. I would prefer at least 10.

**Comment by Ian3110** [comment]
I have opened a pull request that addresses this issue: #4668
