### ISSUE TITLE
id "input.file.name" in the documentation of Spring Batch Integration is not valid [BATCH-2719]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#888]
**[Constantino Cronemberger](https://jira.spring.io/secure/ViewProfile.jspa?name=ccronemberger)** opened **[BATCH-2719](https://jira.spring.io/browse/BATCH-2719?redirect=false)** and commented

When I use "input.file.name" with the following code:

```java
@Bean
@StepScope
public ItemReader sampleReader(@Value("#{jobParameters[input.file.name]}") String resource) {
...
    FlatFileItemReader flatFileItemReader = new FlatFileItemReader();
    flatFileItemReader.setResource(new FileSystemResource(resource));
...
    return flatFileItemReader;
}
```

I get the following error:

```java
Caused by: java.lang.IllegalArgumentException: Path must not be null
	at org.springframework.util.Assert.notNull(Assert.java:193) ~[spring-core-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.core.io.FileSystemResource.<init>(FileSystemResource.java:86) ~[spring-core-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at hello.BatchConfigurer.reader(BatchConfigurer.java:89) ~[classes/:na]
```

Using the name "input_file_name" it works.

This string appears in two places, in the `@Value` annotation and in the call to jobParametersBuilder.addString.

---

**Reference URL:** https://github.com/spring-projects/spring-batch/blob/master/spring-batch-docs/asciidoc/spring-batch-integration.adoc

**Comment by benas** [comment]
The documentation seems correct to me:

1. The `FileParameterName` in `FileMessageToJobRequest` is set to `input.file.name` [here](https://docs.spring.io/spring-batch/docs/4.2.x/reference/html/spring-batch-integration.html#spring-batch-integration-configuration)
2. A job parameter named `input.file.name` is set  with the absolute path of the message payload [here](https://docs.spring.io/spring-batch/docs/4.2.x/reference/html/spring-batch-integration.html#transforming-a-file-into-a-joblaunchrequest)
3. The reader in the [example](https://docs.spring.io/spring-batch/docs/4.2.x/reference/html/spring-batch-integration.html#example-itemreader-configuration) is configured to read a job parameter named `input.file.name`

The error `Path must not be null` means the job parameter passed to the reader is `null` (aka the message payload which is supposed to be the absolute path to the file is `null`). Make sure your SI inbound file Adapter is correctly returning the absolute file name.

> Using the name "input_file_name" it works.

I don't think this is related to the issue, otherwise please provide a minimal example that works with `input_file_name` and fails with `input.file.name`. The file parameter name can be anything you want as long as the same value is passed as a parameter to the job and used in the SpEL expression of the reader configuration.

A complete example using `input.file.name` can be found [in this repo](https://github.com/chrisjs/spring-batch-scaling/blob/master/message-job-launch/src/main/resources/META-INF/spring/config/integration.xml#L36).
