### ISSUE TITLE
Aggregate execution context on RemoteStepExecutionAggregator

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#924]
**[Leonardo Diniz](https://jira.spring.io/secure/ViewProfile.jspa?name=leogdiniz)** opened **[BATCH-2684](https://jira.spring.io/browse/BATCH-2684?redirect=false)** and commented

Sometimes when using remote partitioning is necessary to share data between the partitions and the master partition step.
An easy way to do it is to add parameters to the step execution context.

Example of the problem:
Master application has a partitioned step that will deploy 4 docker images.
Each image will execute a partition of the master partitioned step. At the end of each partition, they will upload a file to s3.  The next step in the master application needs to know where this file is, or download it. If you add this information to the step context it won't be aggregated with the current implementation of RemoteStepExecutionAggregator.

---

**Referenced from:** pull request https://github.com/spring-projects/spring-batch/pull/585

**Comment by taxone** [comment]
I encountered the same issue using Spring Cloud Task with Kubernetes, you can find details here in [this Stack Overflow question](https://stackoverflow.com/questions/65886489/step-executioncontext-not-promoted-using-spring-cloud-task-on-spring-cloud-data) opened by me.

Each worker could write the result of its partitioned execution and this result could be available to the next step.
For example, the  workerTasklet writes a result and  aggregator tasklet  (executed as last step of the job) reads all the results:

```
     @Bean
	public Tasklet workerTasklet() {
		return new Tasklet() {
			@Override
			public RepeatStatus execute(StepContribution contribution, ChunkContext chunkContext) throws Exception {
				ExecutionContext executionContext = chunkContext.getStepContext().getStepExecution()
						.getExecutionContext();
				Integer partitionNumber = executionContext.getInt("partitionNumber");
				System.out.println("This tasklet ran partition UPD1: " + partitionNumber);
				executionContext.put(RESULT_PREFIX + partitionNumber, "myResult " + partitionNumber);

				return RepeatStatus.FINISHED;
			}
		};
	}
       @Bean
	public Tasklet aggregatorTasklet() {
		return (contribution, chunkContext) -> {
			Map<String, Object> jobExecutionContext = chunkContext.getStepContext().getJobExecutionContext();
			
			jobExecutionContext.entrySet().stream().forEach(e -> {
				System.out.println(e.getKey()+": "+e.getValue());
			});

			System.out.println("Last step executed");
			return RepeatStatus.FINISHED;
		};
	}
```

**Comment by fmbenhassine** [comment]
The `RemoteStepExecutionAggregator` is not designed to do the aggregation itself, so this should be done in a custom aggregator to use as a delegate.

Now since the aggregation logic can be specific and may vary depending on several parameters (dynamic key patterns, worker statuses, etc), I don't think this feature should be implemented in the framework but rather left to the user with a custom aggregator.

Based on the given use case, if keys on the worker side are like `partition1:file`, `partition2:file`, etc, one can use pattern to select the keys to promote to the manager's context (like `partition*:file`).

Here is a quick custom aggregator for that:

```java
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import org.springframework.batch.core.StepExecution;
import org.springframework.batch.support.PatternMatcher;

public class ExecutionContextAggregator extends DefaultStepExecutionAggregator {

	private List<String> keyPatterns = new ArrayList<>();

	public void setKeyPatterns(List<String> keyPatterns) {
		this.keyPatterns = keyPatterns;
	}

	@Override
	public void aggregate(StepExecution result, Collection<StepExecution> executions) {
		super.aggregate(result, executions);
		for (String keyPattern : keyPatterns) {
			for (StepExecution stepExecution : executions) {
				stepExecution.getExecutionContext().entrySet()
						.stream().filter(entry -> PatternMatcher.match(keyPattern, entry.getKey()))
						.forEach(entry -> result.getExecutionContext().put(entry.getKey(), entry.getValue()));
			}
		}
	}
}
```

This aggregator promotes any key that matches one of the given patterns from worker contexts to the manager's context.

I am closing this request for now, but if someone finds a generic way that could be added to the framework, I would be open to consider it.
